# Generated by Django 5.2.4 on 2025-07-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('mapa', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('imagen', models.ImageField(default='eventos/default.jpg', upload_to='eventos/')),
                ('categoria', models.ManyToManyField(to='bckaqphoy.categoria', verbose_name='Categorías del evento')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bckaqphoy.lugar')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bckaqphoy.organizador', verbose_name='Organizador del evento')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
